apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  ports:
    - port: 8080
  selector:
    app: blog
    tier: app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
      tier: app
  template:
    metadata:
      labels:
        app: blog
        tier: app
    spec:
      containers:
        - image: blog
          imagePullPolicy: Never
          name: blog
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 20Mi
          ports:
            - containerPort: 8080
              name: blog
          livenessProbe:
            httpGet:
              path: /server/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 60 # 開発環境ではアクセスログが大量に流れないように間隔を長くしておく
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
      volumes:
        - name: blog-app-secret-volume
          secret:
            secretName: blog-app-secret
